### ISSUE TITLE
Toolbar showing unintelligible buttons

### ISSUE THREAD

**Issue by markcarroll** [ryanmcalister/unotes#11]
When I opened an existing README.md file in UNotes editor, the toolbar shows unrecognizable button glyphs.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/599566/57977820-2f3bcb00-79b5-11e9-9ad8-1579b6bea0c8.png">

**Comment by ryan-mcalister** [comment]
Haven't been able to reproduce... does continue to happen? What platform?

**Comment by markcarroll** [comment]
Just installed on a second machine with exactly the same results. Running Mac OS X 10.14.4 and VS Code 1.34

**Comment by ryan-mcalister** [comment]
I was able to test on Mac OS X Mavericks w/ VS Code 1.34 and wasn't able to reproduce. I'll try on a newer Mac OS X. You could try enabling the display2x setting. That might help.

**Comment by ryanmcalister** [comment]
This is probably a issue related to high dpi displays not being detected. I can reproduce this in Windows when turning on 2x scaling. Working on a fix...
A work-around should be to turn on unotes.editor.display2X in settings.

**Comment by ryanmcalister** [comment]
@markcarroll Please try this version and let me know if it fixes the issue.
[Unotes-1.0.7-rc1.vsix.zip](https://github.com/ryanmcalister/unotes/files/3205414/Unotes-1.0.7-rc1.vsix.zip)

**Comment by markcarroll** [comment]
I tried the fix and it does indeed do the same as the 2X setting and now I can see the buttons correctly. However, the toolbar is relatively huge now.  It seems like it is showing the toolbar at twice the size rather than showing the buttons at twice the density. See screenshot, left is the new one, right is the old one. 
<img width="1032" alt="Screen Shot 2019-05-21 at 8 26 49 PM" src="https://user-images.githubusercontent.com/599566/58145555-6b666a00-7c07-11e9-9641-52b8118400c1.png">

**Comment by ryanmcalister** [comment]
Thanks @markcarroll . [v1.0.8](https://github.com/ryanmcalister/unotes/releases/tag/v1.0.8) should fix the issue.

**Comment by markcarroll** [comment]
Works perfectly. Closing. Thank you for the fast turn around.
