### ISSUE TITLE
Cursor caret goes to beginning of file each 3-4 written chars, or even simply by clicking with mouse.

### ISSUE THREAD

**Issue by marco-sanjuan** [ryanmcalister/unotes#113]
Hi, and thanks for a great tool!

I'm experiencing a weird behaviour. Each time I type some chars, caret goes to begining of file, and also removes some of that written chars. This happens even sometimes without writting, with a simple clicking with mouse.

This occurs in both the WYSIWYG view and the markdown view.

I tried uninstalling unotes, deleting plugin folder and reinstalling. Even tried the Piyush fork with same result.

I'm not sure if problem is in UNotes or VSCode, but this doesn't happens with other files and plugins.

Hope anyone can help, i'm turning mad. Thanks!

Windows 10 Pro
VSCode 1.63.0
UNotes 1.3.1

**Comment by marco-sanjuan** [comment]
I donn't know why but today I have not had the problem... let's see tomorrow....

**Comment by marco-sanjuan** [comment]
Today, started the issue again from the first VSCode startup....

**Comment by marco-sanjuan** [comment]
Today I uninstalled VSCode, removed all vscode configuration/hidden files from my personal folder, and made a fresh installation with only UNotes plugin.

Same issue... 

Can not figure out what is happening here...

**Comment by ryanmcalister** [comment]
I'm having trouble reproducing this issue in Windows and Linux (haven't tried with mac). I do experience a loss of focus when vscode first gets focus and haven't found a solution for that yet. They might be related.

**Comment by marco-sanjuan** [comment]
> 

Great, tell me if i can help

**Comment by EdgarRueda** [comment]
presento el mismo problema, al intentar escribir, el mouse del cursos se va al inicio de la nota

**Comment by ryan-mcalister** [comment]
I noticed this happening when Steam was opened. Closing Steam seemed to fix the issue.

**Comment by marco-sanjuan** [comment]
I don't have Steam installed, hope it helps.
