### ISSUE TITLE
cursor del mouse se va al inicio de la note

### ISSUE THREAD

**Issue by EdgarRueda** [ryanmcalister/unotes#118]

**Comment by xyvyx1** [comment]
yes, mine does this too.  Sometimes.  
It seems that when my cursor is in the WYSIWYG mode, the cursor will jump back to the top every 10 seconds.  This timing is consistent.   If I'm in the middle of typing anything or copy/pasting any content, it behaves as if some ghost is hitting CTRL + Home.  This is maddening. 

If I leave the cursor alone, blinking wherever on the page, it'll just disappear.  I can then hit one of the arrow-keys & the window will scroll up to where the cursor is.  I was able to create several pages of content last week w/o problems.  But it's basically unusable now.  I've rebooted, attempted to close every other app running, ran VSCode as admin, etc... no difference.
