### ISSUE TITLE
Feature: Add option "open with Unotes" when right clicking .md file

### ISSUE THREAD

**Issue by AndrewLaganaro** [ryanmcalister/unotes#123]
### Add option "open with Unotes" when right clicking .md file

It would be really useful if I could simply open any .md file with right click and set Unotes as default editor for markdown files, for this, I think Unotes should be registered as an "editor" like Vscode calls it

Example of what happens when I click in "open with..." on a .md file:

![image](https://user-images.githubusercontent.com/45211616/163890106-ca2c9101-afbd-4abd-b089-183d9d2622c8.png)

I should also be able to set Unotes as default editor.

**Comment by AndrewLaganaro** [comment]
Any comments on this feature suggestion? It's been considered to be added? :)

**Comment by ryanmcalister** [comment]
Thanks for the suggestion. I've been investigating how to implement it. I can add a right-click menu option to open the markdown in the single unotes window without difficulty. To register unotes as a general markdown editor, on the other hand, requires a bit more re-engineering under the hood. I think it's a good suggestion and I'll try and make it happen.

**Comment by AndrewLaganaro** [comment]
In fact, just clicking the file and going to the Unotes editor is what I'd want, it would greatly improve my workflow. If you can do that of the option on the right click menu I'd be more than happy to test here as an update.

Also, another suggestion: I don't use Unotes sidebar at all, just cuz I'm obliged to go to it to open the file. Just for you to know, if that option to open in the menu comes to reality, I'd disable the sidebar/side icon to give place to others that I need the most but are hidden right now 🤣

In fact the perfect solution would be registering Unotes as a general markdown editor anyway, but everything at it's time! If you have any news, pls comment for us to know.

**Comment by ryanmcalister** [comment]
[Unotes-latest-1.4.2.1.vsix.zip](https://github.com/ryanmcalister/unotes/files/8585931/Unotes-latest-1.4.2.1.vsix.zip)
@AndrewLaganaro Here is a test version with the right-click menu option.

**Comment by AndrewLaganaro** [comment]
How do I install it?

**Comment by ryanmcalister** [comment]
You can use the extensions menu command 'Install from VSIX...'

**Comment by kiyoka** [comment]
@ryanmcalister 
This issue has been resolved and should be closed.
