### ISSUE TITLE
Feature Request: Prevent image duplication when dragging and dropping image files in the media folder.

### ISSUE THREAD

**Issue by kiyoka** [ryanmcalister/unotes#133]
When I drag and drop an image from the media folder, I want it to be assumed that I am reusing the same image.

## Current behavior (Unotes v1.4.3)
1. the media folder setting is "./img"
![image](https://user-images.githubusercontent.com/80378/184054337-f4da556c-cb24-49b5-9228-b41268d75fbb.png)

2. Drop and drop the file "./img/green1.png"
![dnd1](https://user-images.githubusercontent.com/80378/183823220-bb89da01-55e7-40d3-9087-646560e7e4ca.png)

3. Unotes duplicates the image and save as "./img/img_0.png"
4. The image link will be as follows.
![dnd2](https://user-images.githubusercontent.com/80378/183823251-7c322bb7-6aed-453b-b528-62cafa2d0777.png)

## Desired behavior
I want it to be markdown as follows.
``` markdown
![green1.png](./img/green1.png)
```
## Implementation plan
We can Implement at onPaste(e) function.
argument `e` has full path of the image file.

**Comment by ryanmcalister** [comment]
I can see how this might fit certain work flows. I think this change is the a good idea. Thanks!
