### ISSUE TITLE
Feature Request: Upgrade tui.editor from version 2.5 to version 3.x

### ISSUE THREAD

**Issue by kiyoka** [ryanmcalister/unotes#137]
## Reasons to upgrade
1. Because tui.editor 2.5 has a bug, so #134 cannot be implemented. tui.editor 3.2 does not have the same bug.

- See also the following comments
https://github.com/ryanmcalister/unotes/issues/134#issuecomment-1221273329

2. The main focus of the tui.editor project has moved to tui.editor 3.x, so any problems in tui.editor 2.5 may not be fixed.

## Required Work
1. Follow the migration guide below.
https://github.com/nhn/tui.editor/blob/master/docs/v3.0-migration-guide.md
I believe it is better to actually do the work to see what kind of work will be involved.

**Comment by kiyoka** [comment]
I share the  current status. 
A few problems remain, but it is mostly working with tui.editor 3.0.0.

https://github.com/kiyoka/unotes/commits/fix_issue_137.tmp1

**Remaining issues:**
- The tui.editor plugin interface has changed, so the katex plugin interface needs to be changed.
- The scroll position moves to the bottom of the page when it is auto-saved. (markdown mode only).
- tui.editor 3.2.0 has a bug as follows, so I decided to use tui.editor 3.0.0 .
https://pullanswer.com/questions/latest-version-has-broken-the-insert-url-link-functionality
- Since tui.editor 3.x now supports dark mode, I would like to change to use it.

**Comment by kiyoka** [comment]
Remaining issues:

- The tui.editor plugin interface has changed, so the katex plugin interface needs to be changed.
- Key bindings like `Ctrl + ALT + 1`, `Ctrl + ALT + 2`, ... do not work.

**Comment by kiyoka** [comment]
**Remaining issues:**

- The tui.editor plugin interface has changed, so the katex plugin interface needs to be changed.

**Comment by kiyoka** [comment]
All remaining issues have been cleared.
I will use new Unotes for a while and if I have no problem using it, I will pull request it.

**Comment by ryanmcalister** [comment]
I'm going to close this since it's been released in v1.5.0
