### ISSUE TITLE
Text is wrong color

### ISSUE THREAD

**Issue by mkanet** [ryanmcalister/unotes#17]
I would really like to use your extension.  However, I can't see the text due to the wrong text color on my theme.  How do I change UNotes text color so I can see it the text?

This is what it looks like:
![image](https://user-images.githubusercontent.com/811008/61504054-da093f00-a98e-11e9-902d-e8edbccd6cf4.png)

**Comment by ryanmcalister** [comment]
What theme are you using? Is this your own custom theme?

**Comment by mkanet** [comment]
Please close this issue.  I was using the wrong base theme.  It's working great now.
