### ISSUE TITLE
Select root path of notes

### ISSUE THREAD

**Issue by epaezrubio** [ryanmcalister/unotes#18]
Hey,

first of all thanks for this extension :) It has a lot of potential and I'm surprised it hasn't received many contributions yet.

For my use case, I don't want to store the notes in my current workspace. Instead I'd like to have a central folder for all shared documentation. This folder I'd pass to the extension by a configuration parameter.

I prepared this https://github.com/epaezrubio/unotes/commit/fe39ffcd5e16ddd894d3f086883183784202632b and it works fine while using the debug vscode task, but I haven't had success installing it once compiled. Also I couldn't find any contribution guide in the project.

Is this feature something you would be up to merge? And if yes, can you maybe give some insights about how to test it in a production-like environment?

Cheers

**Comment by ryanmcalister** [comment]
@epaezrubio this looks great! Thanks! I'd be willing to merge it in if you submit a pull request. Sorry the project isn't very contributor-friendly yet. I'll work on creating a contribution guide as soon as possible.

**Comment by epaezrubio** [comment]
Fixed on #19
