### ISSUE TITLE
Configurable note file extension (.txt vs .md)

### ISSUE THREAD

**Issue by brx75** [ryanmcalister/unotes#30]
Hi, 
thank you for this extension.This is something I was looking for since months. 
I've an enhancement request for you. It would be possible to have note file extensions configurable?
I always use .txt as extension even for markdown files and thus they are not visible from the "note browser" view.
Thanks.

**Comment by ryanmcalister** [comment]
Thanks for the request. This seems like a good enhancement and quite simple to add as a user setting.

**Comment by ryanmcalister** [comment]
Added in v1.1.2

**Comment by ryanmcalister** [comment]
Closing because it's been implemented and released.
