### ISSUE TITLE
Files do not show when using subst / virtual drive

### ISSUE THREAD

**Issue by welford** [ryanmcalister/unotes#31]
I have a logical drive e.g. c:/abc/def/ mapped to n:/ via ``SUBST n: %~dp0.``, when i open n:\ with Code this extension does not show any files.

**Comment by ryanmcalister** [comment]
This should be fixed in v1.1.2.

**Comment by ryanmcalister** [comment]
Closing because it's been implemented and released. Let me know if it's still not working.

**Comment by welford** [comment]
works perfectly, thanks.
