### ISSUE TITLE
How to specify media folder/directory instead of .media

### ISSUE THREAD

**Issue by albertyckwok** [ryanmcalister/unotes#45]
Hi, I am wondering if it is possible to change the directory where unotes save/convert pictures. The default is .media. I would like to make it visible, e.g. media or images.

Thanks very much in advance
Albert

**Comment by ryanmcalister** [comment]
Currently the media folder is not configurable. I can look at making it a user setting.

**Comment by albertyckwok** [comment]
Thanks for the info. Let me know if there is anything I can do to help.

**Comment by ryanmcalister** [comment]
Implemented in 1.1.5
