### ISSUE TITLE
Problem:Unreadable Chinese characters

### ISSUE THREAD

**Issue by 1024th** [ryanmcalister/unotes#6]
When I try to open a markdown file with Chinese characters in it, something happened like it is opened in a wrong encoding.

Edit and save with vscode:
![image](https://user-images.githubusercontent.com/47070449/56646419-1c81ef00-66b2-11e9-8211-4161ae9955ed.png)

Then open with unotes:
![image](https://user-images.githubusercontent.com/47070449/56646437-24419380-66b2-11e9-8982-0060721ccd57.png)

And as long as I save it in unotes, reopen it in vscode or other editors, it will look like this:
![image](https://user-images.githubusercontent.com/47070449/56646654-8a2e1b00-66b2-11e9-82ce-efdc003e450b.png)

But when I type in Chinese characters in unotes and save it, then open it with other editors, it seems that nothing goes wrong:
![image](https://user-images.githubusercontent.com/47070449/56646731-b77ac900-66b2-11e9-9976-082fd60a033b.png)
![image](https://user-images.githubusercontent.com/47070449/56646980-38d25b80-66b3-11e9-93c7-e2dcc2687d6d.png)

**Comment by ryanmcalister** [comment]
This will be fixed shortly in unotes v.1.0.5. 
Thanks for the issue report!
