### ISSUE TITLE
VIM keybinding  support

### ISSUE THREAD

**Issue by htjain** [ryanmcalister/unotes#64]
I am missing my vim keybindings support in notes editor. 
Is it possible to get vim keys working I already have vim plugin installed?

**Comment by ryan-mcalister** [comment]
Unfortunately it isn't possible. The vim plugin only works for editor windows in vs code. The Unotes editor is a WebView window and doesn't work the same way as editor windows.

**Comment by htjain** [comment]
fair enough.  Is it possible to add spell checker ?

**Comment by htjain** [comment]
https://github.com/ryanmcalister/unotes/issues/66
