### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by gkoulin** [ryanmcalister/unotes#79]
Would be nice if there was a way to setup shortcuts for the various styling buttons.
i.e. CMD+B for bold

**Comment by ryanmcalister** [comment]
You should already be able to setup shortcuts using the VSCode Keyboard Shortcuts settings. Just search for `unotes`.
![image](https://user-images.githubusercontent.com/19506053/86484294-27eb9400-bd13-11ea-8ce5-5947b48dc8ce.png)
