### ISSUE TITLE
Copy-Paste broken with VS Code version 1.47.0

### ISSUE THREAD

**Issue by epikgit** [ryanmcalister/unotes#80]
I've just updated my VS Code to 1.47.0 and now unotes is behaving strangely.
If I copy a text from everywhere and then I paste in the wysiwyg unotes editor, it pastes the text twice.
If I paste the text in the raw unotes editor, it pastes it twice again.
If I paste the same text (same clipboard) in the VS Code editor, it pastes it once.
What is happening here?

**Comment by ryanmcalister** [comment]
This looks like a vscode bug. in 1.47.0
https://github.com/microsoft/vscode/issues/101946
Looks like it should be fixed in the next update.
One work-around might be to delete the keybinding for `paste`

**Comment by ryanmcalister** [comment]
Looks like this issue was fixed in vscode 1.47.2
https://github.com/microsoft/vscode/issues?q=is:issue+milestone:%22June+2020+Recovery+2%22+is:closed

**Comment by epikgit** [comment]
Yes I confirm that. Issue solved.
Thank you!
