### ISSUE TITLE
New Images link show broken icon upon paste

### ISSUE THREAD

**Issue by joshuaquek** [ryanmcalister/unotes#82]
When I paste an image in, it renders for like a second and the disappears and I get this:
![image](https://user-images.githubusercontent.com/5335756/88473665-5cd5ba00-cf52-11ea-835a-c70cbffff465.png)

This is what it looks like in the code view:
![image](https://user-images.githubusercontent.com/5335756/88473682-927aa300-cf52-11ea-97c7-edb3f9523818.png)

However, when I preview it with my other Markdown previewing tool, it shows the images rendering properly:
![image](https://user-images.githubusercontent.com/5335756/88473677-88f13b00-cf52-11ea-9296-9d067a8de746.png)

Is anyone else experiencing the issue? I tried uninstalling and reinstalling Unotes but to no avail.

**Comment by ryanmcalister** [comment]
Thanks for the report. I noticed this started happening after updating to VS code 1.47. Seems like it works in Windows but not Linux. 
I will look into a way to fix it...

**Comment by joshuaquek** [comment]
Sure, thank you @ryanmcalister . I am using MacOSX Catalina at the moment.

**Comment by ryanmcalister** [comment]
@joshuaquek This should be fixed now in v1.1.8.

**Comment by ryanmcalister** [comment]
I'm going to close this because it is fixed now. Let me know if there are still issues.

**Comment by joshuaquek** [comment]
Works on my end already. Thanks!
