### ISSUE TITLE
Action Bar Color Theme

### ISSUE THREAD

**Issue by jd-carroll** [ryanmcalister/unotes#91]
The action bar color theme comes by default in a dark theme, is there any chance it could not be a dark theme?  It is very difficult to read the button options when not using a dark theme.

![image](https://user-images.githubusercontent.com/1885864/97360464-7c36f880-185b-11eb-8b9c-8a1c036a06eb.png)

**Comment by alexander-gorelik** [comment]
Same here and the tables outlines are not visible at all
