### ISSUE TITLE
Better documentation for table editor

### ISSUE THREAD

**Issue by JarnoRFB** [ryanmcalister/unotes#94]
First of all thanks for this great extension, I have been looking for something like this for a long time!

The main reason, why I need a visual editor for markdown, is because table are always a pain to edit in raw text. However, when I first started editing tables with unotes I was a afraid that I was stuck with the original table size, because I could not find the right click menu on the table. So I think it would be great if this could be somehow documented in README with a screenshot.

**Comment by ryan-mcalister** [comment]
Thanks for the suggestion!

**Comment by ryanmcalister** [comment]
Added documentation in the README. Thanks for the suggestion.
